\newcommand{\C}{\mathbb{C}}
\newcommand{\Cn}{\mathbb{C}^n}
\newcommand{\R}{\mathbb{R}}
\newcommand{\Rn}{\mathbb{R}^n}
\newcommand{\Hilbert}{\mathcal{H}}
\newcommand{\ci}{\dot{\imath}}
\newcommand{\stdbase}{\left\langle \textbf{e}_k \right\rangle_{1\leq k\leq n}}
\newcommand{\stdbaseelem}[1]{\left\langle \textbf{e}_{#1} \right\rangle}

\newcommand*\ieval[3]{\left.#1\right\rvert_{#2}^{#3}}
\newcommand*\ievalsimple[1]{#1 \Big|_{#1_a}^{#1_b}}

\newcommand{\centered}[1]{\begin{tabular}{l} #1 \end{tabular}}

\newcommand{\parentheses}[1]{\left( #1 \right)}